Feature: event issuer for dummies
Bane-NOR/event-issuer pull request #1
Opened 2023-10-16 06:45 UTC by melanki

Edited navigation menu and written introduction to Event Issuer.

2023-10-16 07:35 UTC, melanki commented
Navigation tabs are being brought back in next PR

2023-10-18 12:37 UTC, schteffy requested changes

2023-10-18 12:37 UTC, schteffy commented on docs/api-versioning.md
> +This API uses semver, and version names follows the `v{major}` format. You can find the versions currently available by using the version selector at the top of this page.
Add link to https://semver.org/ for transparency, e.g.: "This API uses [semver](https://semver.org/), and (...)"

2023-10-18 13:35 UTC, schteffy approved these changes

2023-10-18 15:13 UTC, idarb-oss approved these changes

2023-10-18 15:13 UTC, merged