Feature: How to connect to event issuer
Bane-NOR/event-issuer pull request #2
Opened 2023-10-16 07:37 UTC by melanki

Documented:
- How to find Event Issuer API in API Manager
- How to create a subscription to relieve events

2023-10-18 15:16 UTC, idarb-oss requested changes

2023-10-18 15:16 UTC, idarb-oss commented on docs/user-guides/getting-started.md
> +    "event": "cloud.operational.event.train-arrived-at-station.v1",
why is cloud part of the event?

2023-10-19 06:25 UTC, schteffy approved these changes
When the the new Developer Portal is live, we should update the pictures in the "how-to guide" so that they correspond to the current design.

2023-10-19 10:33 UTC, melanki commented on docs/user-guides/getting-started.md
> +    "event": "cloud.operational.event.train-arrived-at-station.v1",
Updated event to exclude environment.

2023-10-23 12:45 UTC, idarb-oss approved these changes

2023-10-23 12:45 UTC, merged